server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: resumeparser
          uri: http://localhost:8081
        - id: gs-uploading-files
          uri: http://localhost:8082
      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloudGateway
